### ISSUE TITLE
Mention embedded-hal dependency in README

### ISSUE THREAD

**Issue by gustavobat** [barafael/ebyte-e32-rs#1]
Hi, @barafael! First of all, I'd like to thank you for open-sourcing your work. It looks exactly like what I need for an upcoming project. In the next couple of weeks I'll test this crate with the E32-900T20D, and if all works fine you can add to the list of tested models :)
 
While reading the description, it wasn't clear to me how your lib interfaces with the MCU code, until I checked the source code/`Cargo.toml` and saw you use `embedded-hal`. 
IMHO mentioning the usage of `embedded-hal` in the README (like you did in the `ebyte-e32-ui` repo) is important and would make it easier for potential users to evaluate how your library can be integrated with their Rust embedded projects, so this is my small two cents on it so far :)

Kind regards

**Comment by barafael** [comment]
Hi Gustavo, that's awesome! Let me know how it goes and if there's any way I can help with testing.

I'll be adding the docs like you said.

**Comment by gustavobat** [comment]
Just confirmed that this crate works fine with the E32-900T20D!
[Here](https://github.com/gustavobat/esp32-ebyte-e32) is a working example with an ESP32 MCU, in case you want to mention in the docs :)

**Comment by barafael** [comment]
Very cool that it works with that module too :) !

**Comment by barafael** [comment]
You didn't happen to test https://github.com/barafael/ebyte-e32-ui ?

**Comment by gustavobat** [comment]
Testing with [ebyte-e32-ui](https://github.com/barafael/ebyte-e32-ui) goes beyond the scope of my experiments at work at the moment. If it test it at some point, I'll let you know! :)
